### ISSUE TITLE
Fix shared integration tests AbstractDocumentFilesAdapterIT for Exasol 8.32.0

### ISSUE THREAD

**Issue by kaklakariada** [exasol/virtual-schema-common-document-files#177]
Exasol 8.32.0 adds support for timestamps with scale, causing shared integration tests in `AbstractDocumentFilesAdapterIT` to fail, e.g.: https://github.com/exasol/s3-document-files-virtual-schema/actions/runs/11897857579/job/33153043630?pr=175

```
 Error:  com.exasol.adapter.document.files.S3DocumentFilesAdapterIT.testReadCsvWithTypesWithHeader -- Time elapsed: 6.032 s <<< ERROR!
java.lang.IllegalStateException: Assertion query 'SELECT str, IS_ACTIVE, decimal_col, int_col, double_col, date_col, timestamp_col FROM TEST.BOOKS' failed: Adapter generated invalid pushdown query for virtual table BOOKS: Data type mismatch in column number 7 (1-indexed). Expected TIMESTAMP(6), but got TIMESTAMP(3). (pushdown query: SELECT "STR", "IS_ACTIVE", "DECIMAL_COL", "INT_COL", "DOUBLE_COL", "DATE_COL", "TIMESTAMP_COL" FROM (SELECT "ADAPTER".IMPORT_FROM_S3_DOCUMENT_FILES("DATA_LOADER", 'rO0ABXNyADhjb20uZXhhc29sLmFkYXB0ZXIuZG9jdW1lbnQubWFwcGluZy5TY2hlbWFNYXBwaW5nUmVxdWVzdOio6FDZAiEzAgACTAAHY29sdW1uc3QAEExqYXZhL3V0aWwvTGlzdDtMABFwYXRoSW5SZW1vdGVUYWJsZXQAQUxjb20vZXhhc29sL2FkYXB0ZXIvZG9jdW1lbnQvZG9jdW1lbnRwYXRoL0RvY3VtZW50UGF0aEV4cHJlc3Npb247eHBzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAB3cEAAAAB3NyAD9jb20uZXhhc29sLmFkYXB0ZXIuZG9jdW1lbnQubWFwcGluZy5Qcm9wZXJ0eVRvRGF0ZUNvbHVtbk1hcHBpbmdVnuvcfTzz4QIAAUwAEG5vdERhdGVCZWhhdmlvdXJ0AENMY29tL2V4YXNvbC9hZGFwdGVyL2RvY3VtZW50L2VkbWwvQ29udmVydGFibGVNYXBwaW5nRXJyb3JCZWhhdmlvdXI7eHIAQ2NvbS5leGFzb2wuYWRhcHRlci5kb2N1bWVudC5tYXBwaW5nLkFic3RyYWN0UHJvcGVydHlUb0NvbHVtbk1hcHBpbme43NImdMJ2ygIAAkwAE2xvb2t1cEZhaWxCZWhhdmlvdXJ0ADhMY29tL2V4YXNvbC9hZGFwdGVyL2RvY3VtZW50L2VkbWwvTWFwcGluZ0Vycm9yQmVoYXZpb3VyO0wAFHBhdGhUb1NvdXJjZVByb3BlcnR5cQB+AAJ4cgA5Y29tLmV4YXNvbC5hZGFwdGVy...) (Session: 1816082935104733184)
	at com.exasol.adapter.document.files.AbstractDocumentFilesAdapterIT.assertQuery(AbstractDocumentFilesAdapterIT.java:994)
	at com.exasol.adapter.document.files.AbstractDocumentFilesAdapterIT.testReadCsvWithTypesWithHeader(AbstractDocumentFilesAdapterIT.java:252)

Error:  com.exasol.adapter.document.files.S3DocumentFilesAdapterIT.testReadParquetFileWithAutomaticInference -- Time elapsed: 10.32 s <<< ERROR!
java.lang.IllegalStateException: Assertion query 'SELECT "DATA", "IS_ACTIVE", "MY_DATE", "MY_TIME", "MY_TIMESTAMP", "JSON" FROM TEST.BOOKS' failed: Adapter generated invalid pushdown query for virtual table BOOKS: Data type mismatch in column number 5 (1-indexed). Expected TIMESTAMP(6), but got TIMESTAMP(3). (pushdown query: SELECT "DATA", "IS_ACTIVE", "MY_DATE", "MY_TIME", "MY_TIMESTAMP", "JSON" FROM (SELECT "ADAPTER".IMPORT_FROM_S3_DOCUMENT_FILES("DATA_LOADER", 'rO0ABXNyADhjb20uZXhhc29sLmFkYXB0ZXIuZG9jdW1lbnQubWFwcGluZy5TY2hlbWFNYXBwaW5nUmVxdWVzdOio6FDZAiEzAgACTAAHY29sdW1uc3QAEExqYXZhL3V0aWwvTGlzdDtMABFwYXRoSW5SZW1vdGVUYWJsZXQAQUxjb20vZXhhc29sL2FkYXB0ZXIvZG9jdW1lbnQvZG9jdW1lbnRwYXRoL0RvY3VtZW50UGF0aEV4cHJlc3Npb247eHBzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAABncEAAAABnNyAEJjb20uZXhhc29sLmFkYXB0ZXIuZG9jdW1lbnQubWFwcGluZy5Qcm9wZXJ0eVRvVmFyY2hhckNvbHVtbk1hcHBpbmcEl/9Dq+hDTwIAA0kAEXZhcmNoYXJDb2x1bW5TaXplTAASbm9uU3RyaW5nQmVoYXZpb3VydABDTGNvbS9leGFzb2wvYWRhcHRlci9kb2N1bWVudC9lZG1sL0NvbnZlcnRhYmxlTWFwcGluZ0Vycm9yQmVoYXZpb3VyO0wAEW92ZXJmbG93QmVoYXZpb3VydABETGNvbS9leGFzb2wvYWRhcHRlci9kb2N1bWVudC9lZG1sL1RydW5jYXRlYWJsZU1hcHBpbmdFcnJvckJlaGF2aW91cjt4cgBDY29tLmV4YXNvbC5hZGFwdGVyLmRvY3VtZW50Lm1hcHBpbmcuQWJzdHJhY3RQcm9wZXJ0eVRvQ29sdW1uTWFwcGluZ7jc0iZ0wnbKAgACTAATbG9va3VwRmFpbEJlaGF2aW91cnQAOExjb20vZX...) (Session: 1816082935104733184)
	at com.exasol.adapter.document.files.AbstractDocumentFilesAdapterIT.assertQuery(AbstractDocumentFilesAdapterIT.java:994)
	at com.exasol.adapter.document.files.AbstractDocumentFilesAdapterIT.testReadParquetFileWithAutomaticInference(AbstractDocumentFilesAdapterIT.java:660)
...

**Comment by pj-spoelders** [comment]
Affected tests in AbstractDocumentFilesAdapterIT:
- testLoadRandomCsvFile
- testReadCsvWithTypesWithHeader
- testReadCsvWithTypesWithoutHeader
- testReadParquetFile
- testReadParquetFileWithAutomaticInference

**Comment by pj-spoelders** [comment]
Temp fix by @skyglass in https://github.com/exasol/virtual-schema-common-document-files/pull/200/changes
